/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StatusRouteImport } from './routes/status'
import { Route as AdminAuditRouteImport } from './routes/_admin.audit'
import { Route as AdminOverviewRouteImport } from './routes/_admin.overview'
import { Route as AdminSettingsRouteImport } from './routes/_admin.settings'
import { Route as AdminApisEndpointsRouteImport } from './routes/_admin.apis.endpoints'
import { Route as AdminApisErrorsRouteImport } from './routes/_admin.apis.errors'
import { Route as AdminApisLatencyRouteImport } from './routes/_admin.apis.latency'
import { Route as AdminApisQuotasRouteImport } from './routes/_admin.apis.quotas'
import { Route as AdminApisRateLimitsRouteImport } from './routes/_admin.apis.rate-limits'
import { Route as AdminApisRequestsRouteImport } from './routes/_admin.apis.requests'
import { Route as AdminBackupsIndexRouteImport } from './routes/_admin.backups.index'
import { Route as AdminBackupsChecksumsRouteImport } from './routes/_admin.backups.checksums'
import { Route as AdminBackupsHistoryRouteImport } from './routes/_admin.backups.history'
import { Route as AdminBackupsJobsRouteImport } from './routes/_admin.backups.jobs'
import { Route as AdminBackupsRestoreTestsRouteImport } from './routes/_admin.backups.restore-tests'
import { Route as AdminDatabaseConnectionsRouteImport } from './routes/_admin.database.connections'
import { Route as AdminDatabaseGrowthRouteImport } from './routes/_admin.database.growth'
import { Route as AdminDatabaseHealthRouteImport } from './routes/_admin.database.health'
import { Route as AdminDatabasePerformanceRouteImport } from './routes/_admin.database.performance'
import { Route as AdminIdentityAdministratorsRouteImport } from './routes/_admin.identity.administrators'
import { Route as AdminIdentityMachineClientsRouteImport } from './routes/_admin.identity.machine-clients'
import { Route as AdminIdentityPermissionsRouteImport } from './routes/_admin.identity.permissions'
import { Route as AdminIdentityRolesRouteImport } from './routes/_admin.identity.roles'
import { Route as AdminIdentityScopesRouteImport } from './routes/_admin.identity.scopes'
import { Route as AdminIdentitySessionsRouteImport } from './routes/_admin.identity.sessions'
import { Route as AdminInfrastructureComputeRouteImport } from './routes/_admin.infrastructure.compute'
import { Route as AdminInfrastructureHostsRouteImport } from './routes/_admin.infrastructure.hosts'
import { Route as AdminInfrastructureNetworkRouteImport } from './routes/_admin.infrastructure.network'
import { Route as AdminInfrastructureServicesRouteImport } from './routes/_admin.infrastructure.services'
import { Route as AdminInfrastructureStorageRouteImport } from './routes/_admin.infrastructure.storage'
import { Route as AdminLicensingIndexRouteImport } from './routes/_admin.licensing.index'
import { Route as AdminLicensingCustomersRouteImport } from './routes/_admin.licensing.customers'
import { Route as AdminLicensingFeaturesRouteImport } from './routes/_admin.licensing.features'
import { Route as AdminLicensingInstallationsRouteImport } from './routes/_admin.licensing.installations'
import { Route as AdminLicensingLeasesRouteImport } from './routes/_admin.licensing.leases'
import { Route as AdminLicensingPlansRouteImport } from './routes/_admin.licensing.plans'
import { Route as AdminLicensingProductsRouteImport } from './routes/_admin.licensing.products'
import { Route as AdminLicensingRevocationsRouteImport } from './routes/_admin.licensing.revocations'
import { Route as AdminObservabilityIndexRouteImport } from './routes/_admin.observability.index'
import { Route as AdminObservabilityAlertsRouteImport } from './routes/_admin.observability.alerts'
import { Route as AdminObservabilityLogsRouteImport } from './routes/_admin.observability.logs'
import { Route as AdminObservabilityMetricsRouteImport } from './routes/_admin.observability.metrics'
import { Route as AdminObservabilityPrometheusRouteImport } from './routes/_admin.observability.prometheus'
import { Route as AdminPkiExpirationRouteImport } from './routes/_admin.pki.expiration'
import { Route as AdminPkiRevocationRouteImport } from './routes/_admin.pki.revocation'
import { Route as AdminPkiRotationRouteImport } from './routes/_admin.pki.rotation'
import { Route as AdminProvidersIndexRouteImport } from './routes/_admin.providers.index'
import { Route as AdminProvidersProviderIdRouteImport } from './routes/_admin.providers.$providerId'
import { Route as AdminSaasClientsRouteImport } from './routes/_admin.saas.clients'
import { Route as AdminSaasInstancesRouteImport } from './routes/_admin.saas.instances'
import { Route as AdminSecurityIndexRouteImport } from './routes/_admin.security.index'
import { Route as AdminSecurityAuthenticationRouteImport } from './routes/_admin.security.authentication'
import { Route as AdminSecurityAuthorizationRouteImport } from './routes/_admin.security.authorization'
import { Route as AdminSecurityEventsRouteImport } from './routes/_admin.security.events'
import { Route as AdminSecurityFailedAttemptsRouteImport } from './routes/_admin.security.failed-attempts'
import { Route as AdminSecurityFirewallRouteImport } from './routes/_admin.security.firewall'
import { Route as AdminSecuritySessionsRouteImport } from './routes/_admin.security.sessions'
import { Route as AdminLicensingLicensesIndexRouteImport } from './routes/_admin.licensing.licenses.index'
import { Route as AdminLicensingLicensesIdRouteImport } from './routes/_admin.licensing.licenses.$id'
import { Route as AdminPkiCertificatesIndexRouteImport } from './routes/_admin.pki.certificates.index'
import { Route as AdminPkiCertificatesIdRouteImport } from './routes/_admin.pki.certificates.$id'
import { Route as AdminSaasApplicationsIndexRouteImport } from './routes/_admin.saas.applications.index'
import { Route as AdminSaasApplicationsIdRouteImport } from './routes/_admin.saas.applications.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApisEndpointsRoute = AdminApisEndpointsRouteImport.update({
  id: '/apis/endpoints',
  path: '/apis/endpoints',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApisErrorsRoute = AdminApisErrorsRouteImport.update({
  id: '/apis/errors',
  path: '/apis/errors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApisLatencyRoute = AdminApisLatencyRouteImport.update({
  id: '/apis/latency',
  path: '/apis/latency',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApisQuotasRoute = AdminApisQuotasRouteImport.update({
  id: '/apis/quotas',
  path: '/apis/quotas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApisRateLimitsRoute = AdminApisRateLimitsRouteImport.update({
  id: '/apis/rate-limits',
  path: '/apis/rate-limits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApisRequestsRoute = AdminApisRequestsRouteImport.update({
  id: '/apis/requests',
  path: '/apis/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBackupsIndexRoute = AdminBackupsIndexRouteImport.update({
  id: '/backups/',
  path: '/backups/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBackupsChecksumsRoute = AdminBackupsChecksumsRouteImport.update({
  id: '/backups/checksums',
  path: '/backups/checksums',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBackupsHistoryRoute = AdminBackupsHistoryRouteImport.update({
  id: '/backups/history',
  path: '/backups/history',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBackupsJobsRoute = AdminBackupsJobsRouteImport.update({
  id: '/backups/jobs',
  path: '/backups/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBackupsRestoreTestsRoute =
  AdminBackupsRestoreTestsRouteImport.update({
    id: '/backups/restore-tests',
    path: '/backups/restore-tests',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminDatabaseConnectionsRoute =
  AdminDatabaseConnectionsRouteImport.update({
    id: '/database/connections',
    path: '/database/connections',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminDatabaseGrowthRoute = AdminDatabaseGrowthRouteImport.update({
  id: '/database/growth',
  path: '/database/growth',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDatabaseHealthRoute = AdminDatabaseHealthRouteImport.update({
  id: '/database/health',
  path: '/database/health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDatabasePerformanceRoute =
  AdminDatabasePerformanceRouteImport.update({
    id: '/database/performance',
    path: '/database/performance',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminIdentityAdministratorsRoute =
  AdminIdentityAdministratorsRouteImport.update({
    id: '/identity/administrators',
    path: '/identity/administrators',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminIdentityMachineClientsRoute =
  AdminIdentityMachineClientsRouteImport.update({
    id: '/identity/machine-clients',
    path: '/identity/machine-clients',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminIdentityPermissionsRoute =
  AdminIdentityPermissionsRouteImport.update({
    id: '/identity/permissions',
    path: '/identity/permissions',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminIdentityRolesRoute = AdminIdentityRolesRouteImport.update({
  id: '/identity/roles',
  path: '/identity/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIdentityScopesRoute = AdminIdentityScopesRouteImport.update({
  id: '/identity/scopes',
  path: '/identity/scopes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIdentitySessionsRoute = AdminIdentitySessionsRouteImport.update({
  id: '/identity/sessions',
  path: '/identity/sessions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInfrastructureComputeRoute =
  AdminInfrastructureComputeRouteImport.update({
    id: '/infrastructure/compute',
    path: '/infrastructure/compute',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminInfrastructureHostsRoute =
  AdminInfrastructureHostsRouteImport.update({
    id: '/infrastructure/hosts',
    path: '/infrastructure/hosts',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminInfrastructureNetworkRoute =
  AdminInfrastructureNetworkRouteImport.update({
    id: '/infrastructure/network',
    path: '/infrastructure/network',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminInfrastructureServicesRoute =
  AdminInfrastructureServicesRouteImport.update({
    id: '/infrastructure/services',
    path: '/infrastructure/services',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminInfrastructureStorageRoute =
  AdminInfrastructureStorageRouteImport.update({
    id: '/infrastructure/storage',
    path: '/infrastructure/storage',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminLicensingIndexRoute = AdminLicensingIndexRouteImport.update({
  id: '/licensing/',
  path: '/licensing/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLicensingCustomersRoute = AdminLicensingCustomersRouteImport.update({
  id: '/licensing/customers',
  path: '/licensing/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLicensingFeaturesRoute = AdminLicensingFeaturesRouteImport.update({
  id: '/licensing/features',
  path: '/licensing/features',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLicensingInstallationsRoute =
  AdminLicensingInstallationsRouteImport.update({
    id: '/licensing/installations',
    path: '/licensing/installations',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminLicensingLeasesRoute = AdminLicensingLeasesRouteImport.update({
  id: '/licensing/leases',
  path: '/licensing/leases',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLicensingPlansRoute = AdminLicensingPlansRouteImport.update({
  id: '/licensing/plans',
  path: '/licensing/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLicensingProductsRoute = AdminLicensingProductsRouteImport.update({
  id: '/licensing/products',
  path: '/licensing/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLicensingRevocationsRoute =
  AdminLicensingRevocationsRouteImport.update({
    id: '/licensing/revocations',
    path: '/licensing/revocations',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminObservabilityIndexRoute = AdminObservabilityIndexRouteImport.update({
  id: '/observability/',
  path: '/observability/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminObservabilityAlertsRoute =
  AdminObservabilityAlertsRouteImport.update({
    id: '/observability/alerts',
    path: '/observability/alerts',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminObservabilityLogsRoute = AdminObservabilityLogsRouteImport.update({
  id: '/observability/logs',
  path: '/observability/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminObservabilityMetricsRoute =
  AdminObservabilityMetricsRouteImport.update({
    id: '/observability/metrics',
    path: '/observability/metrics',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminObservabilityPrometheusRoute =
  AdminObservabilityPrometheusRouteImport.update({
    id: '/observability/prometheus',
    path: '/observability/prometheus',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminPkiExpirationRoute = AdminPkiExpirationRouteImport.update({
  id: '/pki/expiration',
  path: '/pki/expiration',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPkiRevocationRoute = AdminPkiRevocationRouteImport.update({
  id: '/pki/revocation',
  path: '/pki/revocation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPkiRotationRoute = AdminPkiRotationRouteImport.update({
  id: '/pki/rotation',
  path: '/pki/rotation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProvidersIndexRoute = AdminProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProvidersProviderIdRoute =
  AdminProvidersProviderIdRouteImport.update({
    id: '/providers/$providerId',
    path: '/providers/$providerId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSaasClientsRoute = AdminSaasClientsRouteImport.update({
  id: '/saas/clients',
  path: '/saas/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSaasInstancesRoute = AdminSaasInstancesRouteImport.update({
  id: '/saas/instances',
  path: '/saas/instances',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityIndexRoute = AdminSecurityIndexRouteImport.update({
  id: '/security/',
  path: '/security/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityAuthenticationRoute =
  AdminSecurityAuthenticationRouteImport.update({
    id: '/security/authentication',
    path: '/security/authentication',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSecurityAuthorizationRoute =
  AdminSecurityAuthorizationRouteImport.update({
    id: '/security/authorization',
    path: '/security/authorization',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSecurityEventsRoute = AdminSecurityEventsRouteImport.update({
  id: '/security/events',
  path: '/security/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityFailedAttemptsRoute =
  AdminSecurityFailedAttemptsRouteImport.update({
    id: '/security/failed-attempts',
    path: '/security/failed-attempts',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSecurityFirewallRoute = AdminSecurityFirewallRouteImport.update({
  id: '/security/firewall',
  path: '/security/firewall',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecuritySessionsRoute = AdminSecuritySessionsRouteImport.update({
  id: '/security/sessions',
  path: '/security/sessions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLicensingLicensesIndexRoute =
  AdminLicensingLicensesIndexRouteImport.update({
    id: '/licensing/licenses/',
    path: '/licensing/licenses/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminLicensingLicensesIdRoute =
  AdminLicensingLicensesIdRouteImport.update({
    id: '/licensing/licenses/$id',
    path: '/licensing/licenses/$id',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminPkiCertificatesIndexRoute =
  AdminPkiCertificatesIndexRouteImport.update({
    id: '/pki/certificates/',
    path: '/pki/certificates/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminPkiCertificatesIdRoute = AdminPkiCertificatesIdRouteImport.update({
  id: '/pki/certificates/$id',
  path: '/pki/certificates/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSaasApplicationsIndexRoute =
  AdminSaasApplicationsIndexRouteImport.update({
    id: '/saas/applications/',
    path: '/saas/applications/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSaasApplicationsIdRoute = AdminSaasApplicationsIdRouteImport.update({
  id: '/saas/applications/$id',
  path: '/saas/applications/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/status': typeof StatusRoute
  '/audit': typeof AdminAuditRoute
  '/overview': typeof AdminOverviewRoute
  '/settings': typeof AdminSettingsRoute
  '/apis/endpoints': typeof AdminApisEndpointsRoute
  '/apis/errors': typeof AdminApisErrorsRoute
  '/apis/latency': typeof AdminApisLatencyRoute
  '/apis/quotas': typeof AdminApisQuotasRoute
  '/apis/rate-limits': typeof AdminApisRateLimitsRoute
  '/apis/requests': typeof AdminApisRequestsRoute
  '/backups/checksums': typeof AdminBackupsChecksumsRoute
  '/backups/history': typeof AdminBackupsHistoryRoute
  '/backups/jobs': typeof AdminBackupsJobsRoute
  '/backups/restore-tests': typeof AdminBackupsRestoreTestsRoute
  '/database/connections': typeof AdminDatabaseConnectionsRoute
  '/database/growth': typeof AdminDatabaseGrowthRoute
  '/database/health': typeof AdminDatabaseHealthRoute
  '/database/performance': typeof AdminDatabasePerformanceRoute
  '/identity/administrators': typeof AdminIdentityAdministratorsRoute
  '/identity/machine-clients': typeof AdminIdentityMachineClientsRoute
  '/identity/permissions': typeof AdminIdentityPermissionsRoute
  '/identity/roles': typeof AdminIdentityRolesRoute
  '/identity/scopes': typeof AdminIdentityScopesRoute
  '/identity/sessions': typeof AdminIdentitySessionsRoute
  '/infrastructure/compute': typeof AdminInfrastructureComputeRoute
  '/infrastructure/hosts': typeof AdminInfrastructureHostsRoute
  '/infrastructure/network': typeof AdminInfrastructureNetworkRoute
  '/infrastructure/services': typeof AdminInfrastructureServicesRoute
  '/infrastructure/storage': typeof AdminInfrastructureStorageRoute
  '/licensing/customers': typeof AdminLicensingCustomersRoute
  '/licensing/features': typeof AdminLicensingFeaturesRoute
  '/licensing/installations': typeof AdminLicensingInstallationsRoute
  '/licensing/leases': typeof AdminLicensingLeasesRoute
  '/licensing/plans': typeof AdminLicensingPlansRoute
  '/licensing/products': typeof AdminLicensingProductsRoute
  '/licensing/revocations': typeof AdminLicensingRevocationsRoute
  '/observability/alerts': typeof AdminObservabilityAlertsRoute
  '/observability/logs': typeof AdminObservabilityLogsRoute
  '/observability/metrics': typeof AdminObservabilityMetricsRoute
  '/observability/prometheus': typeof AdminObservabilityPrometheusRoute
  '/pki/expiration': typeof AdminPkiExpirationRoute
  '/pki/revocation': typeof AdminPkiRevocationRoute
  '/pki/rotation': typeof AdminPkiRotationRoute
  '/providers/$providerId': typeof AdminProvidersProviderIdRoute
  '/saas/clients': typeof AdminSaasClientsRoute
  '/saas/instances': typeof AdminSaasInstancesRoute
  '/security/authentication': typeof AdminSecurityAuthenticationRoute
  '/security/authorization': typeof AdminSecurityAuthorizationRoute
  '/security/events': typeof AdminSecurityEventsRoute
  '/security/failed-attempts': typeof AdminSecurityFailedAttemptsRoute
  '/security/firewall': typeof AdminSecurityFirewallRoute
  '/security/sessions': typeof AdminSecuritySessionsRoute
  '/backups/': typeof AdminBackupsIndexRoute
  '/licensing/': typeof AdminLicensingIndexRoute
  '/observability/': typeof AdminObservabilityIndexRoute
  '/providers/': typeof AdminProvidersIndexRoute
  '/security/': typeof AdminSecurityIndexRoute
  '/licensing/licenses/$id': typeof AdminLicensingLicensesIdRoute
  '/pki/certificates/$id': typeof AdminPkiCertificatesIdRoute
  '/saas/applications/$id': typeof AdminSaasApplicationsIdRoute
  '/licensing/licenses/': typeof AdminLicensingLicensesIndexRoute
  '/pki/certificates/': typeof AdminPkiCertificatesIndexRoute
  '/saas/applications/': typeof AdminSaasApplicationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/status': typeof StatusRoute
  '/audit': typeof AdminAuditRoute
  '/overview': typeof AdminOverviewRoute
  '/settings': typeof AdminSettingsRoute
  '/apis/endpoints': typeof AdminApisEndpointsRoute
  '/apis/errors': typeof AdminApisErrorsRoute
  '/apis/latency': typeof AdminApisLatencyRoute
  '/apis/quotas': typeof AdminApisQuotasRoute
  '/apis/rate-limits': typeof AdminApisRateLimitsRoute
  '/apis/requests': typeof AdminApisRequestsRoute
  '/backups/checksums': typeof AdminBackupsChecksumsRoute
  '/backups/history': typeof AdminBackupsHistoryRoute
  '/backups/jobs': typeof AdminBackupsJobsRoute
  '/backups/restore-tests': typeof AdminBackupsRestoreTestsRoute
  '/database/connections': typeof AdminDatabaseConnectionsRoute
  '/database/growth': typeof AdminDatabaseGrowthRoute
  '/database/health': typeof AdminDatabaseHealthRoute
  '/database/performance': typeof AdminDatabasePerformanceRoute
  '/identity/administrators': typeof AdminIdentityAdministratorsRoute
  '/identity/machine-clients': typeof AdminIdentityMachineClientsRoute
  '/identity/permissions': typeof AdminIdentityPermissionsRoute
  '/identity/roles': typeof AdminIdentityRolesRoute
  '/identity/scopes': typeof AdminIdentityScopesRoute
  '/identity/sessions': typeof AdminIdentitySessionsRoute
  '/infrastructure/compute': typeof AdminInfrastructureComputeRoute
  '/infrastructure/hosts': typeof AdminInfrastructureHostsRoute
  '/infrastructure/network': typeof AdminInfrastructureNetworkRoute
  '/infrastructure/services': typeof AdminInfrastructureServicesRoute
  '/infrastructure/storage': typeof AdminInfrastructureStorageRoute
  '/licensing/customers': typeof AdminLicensingCustomersRoute
  '/licensing/features': typeof AdminLicensingFeaturesRoute
  '/licensing/installations': typeof AdminLicensingInstallationsRoute
  '/licensing/leases': typeof AdminLicensingLeasesRoute
  '/licensing/plans': typeof AdminLicensingPlansRoute
  '/licensing/products': typeof AdminLicensingProductsRoute
  '/licensing/revocations': typeof AdminLicensingRevocationsRoute
  '/observability/alerts': typeof AdminObservabilityAlertsRoute
  '/observability/logs': typeof AdminObservabilityLogsRoute
  '/observability/metrics': typeof AdminObservabilityMetricsRoute
  '/observability/prometheus': typeof AdminObservabilityPrometheusRoute
  '/pki/expiration': typeof AdminPkiExpirationRoute
  '/pki/revocation': typeof AdminPkiRevocationRoute
  '/pki/rotation': typeof AdminPkiRotationRoute
  '/providers/$providerId': typeof AdminProvidersProviderIdRoute
  '/saas/clients': typeof AdminSaasClientsRoute
  '/saas/instances': typeof AdminSaasInstancesRoute
  '/security/authentication': typeof AdminSecurityAuthenticationRoute
  '/security/authorization': typeof AdminSecurityAuthorizationRoute
  '/security/events': typeof AdminSecurityEventsRoute
  '/security/failed-attempts': typeof AdminSecurityFailedAttemptsRoute
  '/security/firewall': typeof AdminSecurityFirewallRoute
  '/security/sessions': typeof AdminSecuritySessionsRoute
  '/backups': typeof AdminBackupsIndexRoute
  '/licensing': typeof AdminLicensingIndexRoute
  '/observability': typeof AdminObservabilityIndexRoute
  '/providers': typeof AdminProvidersIndexRoute
  '/security': typeof AdminSecurityIndexRoute
  '/licensing/licenses/$id': typeof AdminLicensingLicensesIdRoute
  '/pki/certificates/$id': typeof AdminPkiCertificatesIdRoute
  '/saas/applications/$id': typeof AdminSaasApplicationsIdRoute
  '/licensing/licenses': typeof AdminLicensingLicensesIndexRoute
  '/pki/certificates': typeof AdminPkiCertificatesIndexRoute
  '/saas/applications': typeof AdminSaasApplicationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/status': typeof StatusRoute
  '/_admin/audit': typeof AdminAuditRoute
  '/_admin/overview': typeof AdminOverviewRoute
  '/_admin/settings': typeof AdminSettingsRoute
  '/_admin/apis/endpoints': typeof AdminApisEndpointsRoute
  '/_admin/apis/errors': typeof AdminApisErrorsRoute
  '/_admin/apis/latency': typeof AdminApisLatencyRoute
  '/_admin/apis/quotas': typeof AdminApisQuotasRoute
  '/_admin/apis/rate-limits': typeof AdminApisRateLimitsRoute
  '/_admin/apis/requests': typeof AdminApisRequestsRoute
  '/_admin/backups/checksums': typeof AdminBackupsChecksumsRoute
  '/_admin/backups/history': typeof AdminBackupsHistoryRoute
  '/_admin/backups/jobs': typeof AdminBackupsJobsRoute
  '/_admin/backups/restore-tests': typeof AdminBackupsRestoreTestsRoute
  '/_admin/database/connections': typeof AdminDatabaseConnectionsRoute
  '/_admin/database/growth': typeof AdminDatabaseGrowthRoute
  '/_admin/database/health': typeof AdminDatabaseHealthRoute
  '/_admin/database/performance': typeof AdminDatabasePerformanceRoute
  '/_admin/identity/administrators': typeof AdminIdentityAdministratorsRoute
  '/_admin/identity/machine-clients': typeof AdminIdentityMachineClientsRoute
  '/_admin/identity/permissions': typeof AdminIdentityPermissionsRoute
  '/_admin/identity/roles': typeof AdminIdentityRolesRoute
  '/_admin/identity/scopes': typeof AdminIdentityScopesRoute
  '/_admin/identity/sessions': typeof AdminIdentitySessionsRoute
  '/_admin/infrastructure/compute': typeof AdminInfrastructureComputeRoute
  '/_admin/infrastructure/hosts': typeof AdminInfrastructureHostsRoute
  '/_admin/infrastructure/network': typeof AdminInfrastructureNetworkRoute
  '/_admin/infrastructure/services': typeof AdminInfrastructureServicesRoute
  '/_admin/infrastructure/storage': typeof AdminInfrastructureStorageRoute
  '/_admin/licensing/customers': typeof AdminLicensingCustomersRoute
  '/_admin/licensing/features': typeof AdminLicensingFeaturesRoute
  '/_admin/licensing/installations': typeof AdminLicensingInstallationsRoute
  '/_admin/licensing/leases': typeof AdminLicensingLeasesRoute
  '/_admin/licensing/plans': typeof AdminLicensingPlansRoute
  '/_admin/licensing/products': typeof AdminLicensingProductsRoute
  '/_admin/licensing/revocations': typeof AdminLicensingRevocationsRoute
  '/_admin/observability/alerts': typeof AdminObservabilityAlertsRoute
  '/_admin/observability/logs': typeof AdminObservabilityLogsRoute
  '/_admin/observability/metrics': typeof AdminObservabilityMetricsRoute
  '/_admin/observability/prometheus': typeof AdminObservabilityPrometheusRoute
  '/_admin/pki/expiration': typeof AdminPkiExpirationRoute
  '/_admin/pki/revocation': typeof AdminPkiRevocationRoute
  '/_admin/pki/rotation': typeof AdminPkiRotationRoute
  '/_admin/providers/$providerId': typeof AdminProvidersProviderIdRoute
  '/_admin/saas/clients': typeof AdminSaasClientsRoute
  '/_admin/saas/instances': typeof AdminSaasInstancesRoute
  '/_admin/security/authentication': typeof AdminSecurityAuthenticationRoute
  '/_admin/security/authorization': typeof AdminSecurityAuthorizationRoute
  '/_admin/security/events': typeof AdminSecurityEventsRoute
  '/_admin/security/failed-attempts': typeof AdminSecurityFailedAttemptsRoute
  '/_admin/security/firewall': typeof AdminSecurityFirewallRoute
  '/_admin/security/sessions': typeof AdminSecuritySessionsRoute
  '/_admin/backups/': typeof AdminBackupsIndexRoute
  '/_admin/licensing/': typeof AdminLicensingIndexRoute
  '/_admin/observability/': typeof AdminObservabilityIndexRoute
  '/_admin/providers/': typeof AdminProvidersIndexRoute
  '/_admin/security/': typeof AdminSecurityIndexRoute
  '/_admin/licensing/licenses/$id': typeof AdminLicensingLicensesIdRoute
  '/_admin/pki/certificates/$id': typeof AdminPkiCertificatesIdRoute
  '/_admin/saas/applications/$id': typeof AdminSaasApplicationsIdRoute
  '/_admin/licensing/licenses/': typeof AdminLicensingLicensesIndexRoute
  '/_admin/pki/certificates/': typeof AdminPkiCertificatesIndexRoute
  '/_admin/saas/applications/': typeof AdminSaasApplicationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/docs'
    | '/login'
    | '/status'
    | '/audit'
    | '/overview'
    | '/settings'
    | '/apis/endpoints'
    | '/apis/errors'
    | '/apis/latency'
    | '/apis/quotas'
    | '/apis/rate-limits'
    | '/apis/requests'
    | '/backups/checksums'
    | '/backups/history'
    | '/backups/jobs'
    | '/backups/restore-tests'
    | '/database/connections'
    | '/database/growth'
    | '/database/health'
    | '/database/performance'
    | '/identity/administrators'
    | '/identity/machine-clients'
    | '/identity/permissions'
    | '/identity/roles'
    | '/identity/scopes'
    | '/identity/sessions'
    | '/infrastructure/compute'
    | '/infrastructure/hosts'
    | '/infrastructure/network'
    | '/infrastructure/services'
    | '/infrastructure/storage'
    | '/licensing/customers'
    | '/licensing/features'
    | '/licensing/installations'
    | '/licensing/leases'
    | '/licensing/plans'
    | '/licensing/products'
    | '/licensing/revocations'
    | '/observability/alerts'
    | '/observability/logs'
    | '/observability/metrics'
    | '/observability/prometheus'
    | '/pki/expiration'
    | '/pki/revocation'
    | '/pki/rotation'
    | '/providers/$providerId'
    | '/saas/clients'
    | '/saas/instances'
    | '/security/authentication'
    | '/security/authorization'
    | '/security/events'
    | '/security/failed-attempts'
    | '/security/firewall'
    | '/security/sessions'
    | '/backups/'
    | '/licensing/'
    | '/observability/'
    | '/providers/'
    | '/security/'
    | '/licensing/licenses/$id'
    | '/pki/certificates/$id'
    | '/saas/applications/$id'
    | '/licensing/licenses/'
    | '/pki/certificates/'
    | '/saas/applications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/docs'
    | '/login'
    | '/status'
    | '/audit'
    | '/overview'
    | '/settings'
    | '/apis/endpoints'
    | '/apis/errors'
    | '/apis/latency'
    | '/apis/quotas'
    | '/apis/rate-limits'
    | '/apis/requests'
    | '/backups/checksums'
    | '/backups/history'
    | '/backups/jobs'
    | '/backups/restore-tests'
    | '/database/connections'
    | '/database/growth'
    | '/database/health'
    | '/database/performance'
    | '/identity/administrators'
    | '/identity/machine-clients'
    | '/identity/permissions'
    | '/identity/roles'
    | '/identity/scopes'
    | '/identity/sessions'
    | '/infrastructure/compute'
    | '/infrastructure/hosts'
    | '/infrastructure/network'
    | '/infrastructure/services'
    | '/infrastructure/storage'
    | '/licensing/customers'
    | '/licensing/features'
    | '/licensing/installations'
    | '/licensing/leases'
    | '/licensing/plans'
    | '/licensing/products'
    | '/licensing/revocations'
    | '/observability/alerts'
    | '/observability/logs'
    | '/observability/metrics'
    | '/observability/prometheus'
    | '/pki/expiration'
    | '/pki/revocation'
    | '/pki/rotation'
    | '/providers/$providerId'
    | '/saas/clients'
    | '/saas/instances'
    | '/security/authentication'
    | '/security/authorization'
    | '/security/events'
    | '/security/failed-attempts'
    | '/security/firewall'
    | '/security/sessions'
    | '/backups'
    | '/licensing'
    | '/observability'
    | '/providers'
    | '/security'
    | '/licensing/licenses/$id'
    | '/pki/certificates/$id'
    | '/saas/applications/$id'
    | '/licensing/licenses'
    | '/pki/certificates'
    | '/saas/applications'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/changelog'
    | '/docs'
    | '/login'
    | '/status'
    | '/_admin/audit'
    | '/_admin/overview'
    | '/_admin/settings'
    | '/_admin/apis/endpoints'
    | '/_admin/apis/errors'
    | '/_admin/apis/latency'
    | '/_admin/apis/quotas'
    | '/_admin/apis/rate-limits'
    | '/_admin/apis/requests'
    | '/_admin/backups/checksums'
    | '/_admin/backups/history'
    | '/_admin/backups/jobs'
    | '/_admin/backups/restore-tests'
    | '/_admin/database/connections'
    | '/_admin/database/growth'
    | '/_admin/database/health'
    | '/_admin/database/performance'
    | '/_admin/identity/administrators'
    | '/_admin/identity/machine-clients'
    | '/_admin/identity/permissions'
    | '/_admin/identity/roles'
    | '/_admin/identity/scopes'
    | '/_admin/identity/sessions'
    | '/_admin/infrastructure/compute'
    | '/_admin/infrastructure/hosts'
    | '/_admin/infrastructure/network'
    | '/_admin/infrastructure/services'
    | '/_admin/infrastructure/storage'
    | '/_admin/licensing/customers'
    | '/_admin/licensing/features'
    | '/_admin/licensing/installations'
    | '/_admin/licensing/leases'
    | '/_admin/licensing/plans'
    | '/_admin/licensing/products'
    | '/_admin/licensing/revocations'
    | '/_admin/observability/alerts'
    | '/_admin/observability/logs'
    | '/_admin/observability/metrics'
    | '/_admin/observability/prometheus'
    | '/_admin/pki/expiration'
    | '/_admin/pki/revocation'
    | '/_admin/pki/rotation'
    | '/_admin/providers/$providerId'
    | '/_admin/saas/clients'
    | '/_admin/saas/instances'
    | '/_admin/security/authentication'
    | '/_admin/security/authorization'
    | '/_admin/security/events'
    | '/_admin/security/failed-attempts'
    | '/_admin/security/firewall'
    | '/_admin/security/sessions'
    | '/_admin/backups/'
    | '/_admin/licensing/'
    | '/_admin/observability/'
    | '/_admin/providers/'
    | '/_admin/security/'
    | '/_admin/licensing/licenses/$id'
    | '/_admin/pki/certificates/$id'
    | '/_admin/saas/applications/$id'
    | '/_admin/licensing/licenses/'
    | '/_admin/pki/certificates/'
    | '/_admin/saas/applications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  DocsRoute: typeof DocsRoute
  LoginRoute: typeof LoginRoute
  StatusRoute: typeof StatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/audit': {
      id: '/_admin/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/overview': {
      id: '/_admin/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/apis/endpoints': {
      id: '/_admin/apis/endpoints'
      path: '/apis/endpoints'
      fullPath: '/apis/endpoints'
      preLoaderRoute: typeof AdminApisEndpointsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/apis/errors': {
      id: '/_admin/apis/errors'
      path: '/apis/errors'
      fullPath: '/apis/errors'
      preLoaderRoute: typeof AdminApisErrorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/apis/latency': {
      id: '/_admin/apis/latency'
      path: '/apis/latency'
      fullPath: '/apis/latency'
      preLoaderRoute: typeof AdminApisLatencyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/apis/quotas': {
      id: '/_admin/apis/quotas'
      path: '/apis/quotas'
      fullPath: '/apis/quotas'
      preLoaderRoute: typeof AdminApisQuotasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/apis/rate-limits': {
      id: '/_admin/apis/rate-limits'
      path: '/apis/rate-limits'
      fullPath: '/apis/rate-limits'
      preLoaderRoute: typeof AdminApisRateLimitsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/apis/requests': {
      id: '/_admin/apis/requests'
      path: '/apis/requests'
      fullPath: '/apis/requests'
      preLoaderRoute: typeof AdminApisRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/backups/': {
      id: '/_admin/backups/'
      path: '/backups'
      fullPath: '/backups/'
      preLoaderRoute: typeof AdminBackupsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/backups/checksums': {
      id: '/_admin/backups/checksums'
      path: '/backups/checksums'
      fullPath: '/backups/checksums'
      preLoaderRoute: typeof AdminBackupsChecksumsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/backups/history': {
      id: '/_admin/backups/history'
      path: '/backups/history'
      fullPath: '/backups/history'
      preLoaderRoute: typeof AdminBackupsHistoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/backups/jobs': {
      id: '/_admin/backups/jobs'
      path: '/backups/jobs'
      fullPath: '/backups/jobs'
      preLoaderRoute: typeof AdminBackupsJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/backups/restore-tests': {
      id: '/_admin/backups/restore-tests'
      path: '/backups/restore-tests'
      fullPath: '/backups/restore-tests'
      preLoaderRoute: typeof AdminBackupsRestoreTestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/database/connections': {
      id: '/_admin/database/connections'
      path: '/database/connections'
      fullPath: '/database/connections'
      preLoaderRoute: typeof AdminDatabaseConnectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/database/growth': {
      id: '/_admin/database/growth'
      path: '/database/growth'
      fullPath: '/database/growth'
      preLoaderRoute: typeof AdminDatabaseGrowthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/database/health': {
      id: '/_admin/database/health'
      path: '/database/health'
      fullPath: '/database/health'
      preLoaderRoute: typeof AdminDatabaseHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/database/performance': {
      id: '/_admin/database/performance'
      path: '/database/performance'
      fullPath: '/database/performance'
      preLoaderRoute: typeof AdminDatabasePerformanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/identity/administrators': {
      id: '/_admin/identity/administrators'
      path: '/identity/administrators'
      fullPath: '/identity/administrators'
      preLoaderRoute: typeof AdminIdentityAdministratorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/identity/machine-clients': {
      id: '/_admin/identity/machine-clients'
      path: '/identity/machine-clients'
      fullPath: '/identity/machine-clients'
      preLoaderRoute: typeof AdminIdentityMachineClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/identity/permissions': {
      id: '/_admin/identity/permissions'
      path: '/identity/permissions'
      fullPath: '/identity/permissions'
      preLoaderRoute: typeof AdminIdentityPermissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/identity/roles': {
      id: '/_admin/identity/roles'
      path: '/identity/roles'
      fullPath: '/identity/roles'
      preLoaderRoute: typeof AdminIdentityRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/identity/scopes': {
      id: '/_admin/identity/scopes'
      path: '/identity/scopes'
      fullPath: '/identity/scopes'
      preLoaderRoute: typeof AdminIdentityScopesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/identity/sessions': {
      id: '/_admin/identity/sessions'
      path: '/identity/sessions'
      fullPath: '/identity/sessions'
      preLoaderRoute: typeof AdminIdentitySessionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/infrastructure/compute': {
      id: '/_admin/infrastructure/compute'
      path: '/infrastructure/compute'
      fullPath: '/infrastructure/compute'
      preLoaderRoute: typeof AdminInfrastructureComputeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/infrastructure/hosts': {
      id: '/_admin/infrastructure/hosts'
      path: '/infrastructure/hosts'
      fullPath: '/infrastructure/hosts'
      preLoaderRoute: typeof AdminInfrastructureHostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/infrastructure/network': {
      id: '/_admin/infrastructure/network'
      path: '/infrastructure/network'
      fullPath: '/infrastructure/network'
      preLoaderRoute: typeof AdminInfrastructureNetworkRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/infrastructure/services': {
      id: '/_admin/infrastructure/services'
      path: '/infrastructure/services'
      fullPath: '/infrastructure/services'
      preLoaderRoute: typeof AdminInfrastructureServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/infrastructure/storage': {
      id: '/_admin/infrastructure/storage'
      path: '/infrastructure/storage'
      fullPath: '/infrastructure/storage'
      preLoaderRoute: typeof AdminInfrastructureStorageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/licensing/': {
      id: '/_admin/licensing/'
      path: '/licensing'
      fullPath: '/licensing/'
      preLoaderRoute: typeof AdminLicensingIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/licensing/customers': {
      id: '/_admin/licensing/customers'
      path: '/licensing/customers'
      fullPath: '/licensing/customers'
      preLoaderRoute: typeof AdminLicensingCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/licensing/features': {
      id: '/_admin/licensing/features'
      path: '/licensing/features'
      fullPath: '/licensing/features'
      preLoaderRoute: typeof AdminLicensingFeaturesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/licensing/installations': {
      id: '/_admin/licensing/installations'
      path: '/licensing/installations'
      fullPath: '/licensing/installations'
      preLoaderRoute: typeof AdminLicensingInstallationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/licensing/leases': {
      id: '/_admin/licensing/leases'
      path: '/licensing/leases'
      fullPath: '/licensing/leases'
      preLoaderRoute: typeof AdminLicensingLeasesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/licensing/plans': {
      id: '/_admin/licensing/plans'
      path: '/licensing/plans'
      fullPath: '/licensing/plans'
      preLoaderRoute: typeof AdminLicensingPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/licensing/products': {
      id: '/_admin/licensing/products'
      path: '/licensing/products'
      fullPath: '/licensing/products'
      preLoaderRoute: typeof AdminLicensingProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/licensing/revocations': {
      id: '/_admin/licensing/revocations'
      path: '/licensing/revocations'
      fullPath: '/licensing/revocations'
      preLoaderRoute: typeof AdminLicensingRevocationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/observability/': {
      id: '/_admin/observability/'
      path: '/observability'
      fullPath: '/observability/'
      preLoaderRoute: typeof AdminObservabilityIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/observability/alerts': {
      id: '/_admin/observability/alerts'
      path: '/observability/alerts'
      fullPath: '/observability/alerts'
      preLoaderRoute: typeof AdminObservabilityAlertsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/observability/logs': {
      id: '/_admin/observability/logs'
      path: '/observability/logs'
      fullPath: '/observability/logs'
      preLoaderRoute: typeof AdminObservabilityLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/observability/metrics': {
      id: '/_admin/observability/metrics'
      path: '/observability/metrics'
      fullPath: '/observability/metrics'
      preLoaderRoute: typeof AdminObservabilityMetricsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/observability/prometheus': {
      id: '/_admin/observability/prometheus'
      path: '/observability/prometheus'
      fullPath: '/observability/prometheus'
      preLoaderRoute: typeof AdminObservabilityPrometheusRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/pki/expiration': {
      id: '/_admin/pki/expiration'
      path: '/pki/expiration'
      fullPath: '/pki/expiration'
      preLoaderRoute: typeof AdminPkiExpirationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/pki/revocation': {
      id: '/_admin/pki/revocation'
      path: '/pki/revocation'
      fullPath: '/pki/revocation'
      preLoaderRoute: typeof AdminPkiRevocationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/pki/rotation': {
      id: '/_admin/pki/rotation'
      path: '/pki/rotation'
      fullPath: '/pki/rotation'
      preLoaderRoute: typeof AdminPkiRotationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/providers/': {
      id: '/_admin/providers/'
      path: '/providers'
      fullPath: '/providers/'
      preLoaderRoute: typeof AdminProvidersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/providers/$providerId': {
      id: '/_admin/providers/$providerId'
      path: '/providers/$providerId'
      fullPath: '/providers/$providerId'
      preLoaderRoute: typeof AdminProvidersProviderIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/saas/clients': {
      id: '/_admin/saas/clients'
      path: '/saas/clients'
      fullPath: '/saas/clients'
      preLoaderRoute: typeof AdminSaasClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/saas/instances': {
      id: '/_admin/saas/instances'
      path: '/saas/instances'
      fullPath: '/saas/instances'
      preLoaderRoute: typeof AdminSaasInstancesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/security/': {
      id: '/_admin/security/'
      path: '/security'
      fullPath: '/security/'
      preLoaderRoute: typeof AdminSecurityIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/security/authentication': {
      id: '/_admin/security/authentication'
      path: '/security/authentication'
      fullPath: '/security/authentication'
      preLoaderRoute: typeof AdminSecurityAuthenticationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/security/authorization': {
      id: '/_admin/security/authorization'
      path: '/security/authorization'
      fullPath: '/security/authorization'
      preLoaderRoute: typeof AdminSecurityAuthorizationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/security/events': {
      id: '/_admin/security/events'
      path: '/security/events'
      fullPath: '/security/events'
      preLoaderRoute: typeof AdminSecurityEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/security/failed-attempts': {
      id: '/_admin/security/failed-attempts'
      path: '/security/failed-attempts'
      fullPath: '/security/failed-attempts'
      preLoaderRoute: typeof AdminSecurityFailedAttemptsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/security/firewall': {
      id: '/_admin/security/firewall'
      path: '/security/firewall'
      fullPath: '/security/firewall'
      preLoaderRoute: typeof AdminSecurityFirewallRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/security/sessions': {
      id: '/_admin/security/sessions'
      path: '/security/sessions'
      fullPath: '/security/sessions'
      preLoaderRoute: typeof AdminSecuritySessionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/licensing/licenses/': {
      id: '/_admin/licensing/licenses/'
      path: '/licensing/licenses'
      fullPath: '/licensing/licenses/'
      preLoaderRoute: typeof AdminLicensingLicensesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/licensing/licenses/$id': {
      id: '/_admin/licensing/licenses/$id'
      path: '/licensing/licenses/$id'
      fullPath: '/licensing/licenses/$id'
      preLoaderRoute: typeof AdminLicensingLicensesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/pki/certificates/': {
      id: '/_admin/pki/certificates/'
      path: '/pki/certificates'
      fullPath: '/pki/certificates/'
      preLoaderRoute: typeof AdminPkiCertificatesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/pki/certificates/$id': {
      id: '/_admin/pki/certificates/$id'
      path: '/pki/certificates/$id'
      fullPath: '/pki/certificates/$id'
      preLoaderRoute: typeof AdminPkiCertificatesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/saas/applications/': {
      id: '/_admin/saas/applications/'
      path: '/saas/applications'
      fullPath: '/saas/applications/'
      preLoaderRoute: typeof AdminSaasApplicationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/saas/applications/$id': {
      id: '/_admin/saas/applications/$id'
      path: '/saas/applications/$id'
      fullPath: '/saas/applications/$id'
      preLoaderRoute: typeof AdminSaasApplicationsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminOverviewRoute: typeof AdminOverviewRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminApisEndpointsRoute: typeof AdminApisEndpointsRoute
  AdminApisErrorsRoute: typeof AdminApisErrorsRoute
  AdminApisLatencyRoute: typeof AdminApisLatencyRoute
  AdminApisQuotasRoute: typeof AdminApisQuotasRoute
  AdminApisRateLimitsRoute: typeof AdminApisRateLimitsRoute
  AdminApisRequestsRoute: typeof AdminApisRequestsRoute
  AdminBackupsChecksumsRoute: typeof AdminBackupsChecksumsRoute
  AdminBackupsHistoryRoute: typeof AdminBackupsHistoryRoute
  AdminBackupsJobsRoute: typeof AdminBackupsJobsRoute
  AdminBackupsRestoreTestsRoute: typeof AdminBackupsRestoreTestsRoute
  AdminDatabaseConnectionsRoute: typeof AdminDatabaseConnectionsRoute
  AdminDatabaseGrowthRoute: typeof AdminDatabaseGrowthRoute
  AdminDatabaseHealthRoute: typeof AdminDatabaseHealthRoute
  AdminDatabasePerformanceRoute: typeof AdminDatabasePerformanceRoute
  AdminIdentityAdministratorsRoute: typeof AdminIdentityAdministratorsRoute
  AdminIdentityMachineClientsRoute: typeof AdminIdentityMachineClientsRoute
  AdminIdentityPermissionsRoute: typeof AdminIdentityPermissionsRoute
  AdminIdentityRolesRoute: typeof AdminIdentityRolesRoute
  AdminIdentityScopesRoute: typeof AdminIdentityScopesRoute
  AdminIdentitySessionsRoute: typeof AdminIdentitySessionsRoute
  AdminInfrastructureComputeRoute: typeof AdminInfrastructureComputeRoute
  AdminInfrastructureHostsRoute: typeof AdminInfrastructureHostsRoute
  AdminInfrastructureNetworkRoute: typeof AdminInfrastructureNetworkRoute
  AdminInfrastructureServicesRoute: typeof AdminInfrastructureServicesRoute
  AdminInfrastructureStorageRoute: typeof AdminInfrastructureStorageRoute
  AdminLicensingCustomersRoute: typeof AdminLicensingCustomersRoute
  AdminLicensingFeaturesRoute: typeof AdminLicensingFeaturesRoute
  AdminLicensingInstallationsRoute: typeof AdminLicensingInstallationsRoute
  AdminLicensingLeasesRoute: typeof AdminLicensingLeasesRoute
  AdminLicensingPlansRoute: typeof AdminLicensingPlansRoute
  AdminLicensingProductsRoute: typeof AdminLicensingProductsRoute
  AdminLicensingRevocationsRoute: typeof AdminLicensingRevocationsRoute
  AdminObservabilityAlertsRoute: typeof AdminObservabilityAlertsRoute
  AdminObservabilityLogsRoute: typeof AdminObservabilityLogsRoute
  AdminObservabilityMetricsRoute: typeof AdminObservabilityMetricsRoute
  AdminObservabilityPrometheusRoute: typeof AdminObservabilityPrometheusRoute
  AdminPkiExpirationRoute: typeof AdminPkiExpirationRoute
  AdminPkiRevocationRoute: typeof AdminPkiRevocationRoute
  AdminPkiRotationRoute: typeof AdminPkiRotationRoute
  AdminProvidersProviderIdRoute: typeof AdminProvidersProviderIdRoute
  AdminSaasClientsRoute: typeof AdminSaasClientsRoute
  AdminSaasInstancesRoute: typeof AdminSaasInstancesRoute
  AdminSecurityAuthenticationRoute: typeof AdminSecurityAuthenticationRoute
  AdminSecurityAuthorizationRoute: typeof AdminSecurityAuthorizationRoute
  AdminSecurityEventsRoute: typeof AdminSecurityEventsRoute
  AdminSecurityFailedAttemptsRoute: typeof AdminSecurityFailedAttemptsRoute
  AdminSecurityFirewallRoute: typeof AdminSecurityFirewallRoute
  AdminSecuritySessionsRoute: typeof AdminSecuritySessionsRoute
  AdminBackupsIndexRoute: typeof AdminBackupsIndexRoute
  AdminLicensingIndexRoute: typeof AdminLicensingIndexRoute
  AdminObservabilityIndexRoute: typeof AdminObservabilityIndexRoute
  AdminProvidersIndexRoute: typeof AdminProvidersIndexRoute
  AdminSecurityIndexRoute: typeof AdminSecurityIndexRoute
  AdminLicensingLicensesIdRoute: typeof AdminLicensingLicensesIdRoute
  AdminPkiCertificatesIdRoute: typeof AdminPkiCertificatesIdRoute
  AdminSaasApplicationsIdRoute: typeof AdminSaasApplicationsIdRoute
  AdminLicensingLicensesIndexRoute: typeof AdminLicensingLicensesIndexRoute
  AdminPkiCertificatesIndexRoute: typeof AdminPkiCertificatesIndexRoute
  AdminSaasApplicationsIndexRoute: typeof AdminSaasApplicationsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminOverviewRoute: AdminOverviewRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminApisEndpointsRoute: AdminApisEndpointsRoute,
  AdminApisErrorsRoute: AdminApisErrorsRoute,
  AdminApisLatencyRoute: AdminApisLatencyRoute,
  AdminApisQuotasRoute: AdminApisQuotasRoute,
  AdminApisRateLimitsRoute: AdminApisRateLimitsRoute,
  AdminApisRequestsRoute: AdminApisRequestsRoute,
  AdminBackupsChecksumsRoute: AdminBackupsChecksumsRoute,
  AdminBackupsHistoryRoute: AdminBackupsHistoryRoute,
  AdminBackupsJobsRoute: AdminBackupsJobsRoute,
  AdminBackupsRestoreTestsRoute: AdminBackupsRestoreTestsRoute,
  AdminDatabaseConnectionsRoute: AdminDatabaseConnectionsRoute,
  AdminDatabaseGrowthRoute: AdminDatabaseGrowthRoute,
  AdminDatabaseHealthRoute: AdminDatabaseHealthRoute,
  AdminDatabasePerformanceRoute: AdminDatabasePerformanceRoute,
  AdminIdentityAdministratorsRoute: AdminIdentityAdministratorsRoute,
  AdminIdentityMachineClientsRoute: AdminIdentityMachineClientsRoute,
  AdminIdentityPermissionsRoute: AdminIdentityPermissionsRoute,
  AdminIdentityRolesRoute: AdminIdentityRolesRoute,
  AdminIdentityScopesRoute: AdminIdentityScopesRoute,
  AdminIdentitySessionsRoute: AdminIdentitySessionsRoute,
  AdminInfrastructureComputeRoute: AdminInfrastructureComputeRoute,
  AdminInfrastructureHostsRoute: AdminInfrastructureHostsRoute,
  AdminInfrastructureNetworkRoute: AdminInfrastructureNetworkRoute,
  AdminInfrastructureServicesRoute: AdminInfrastructureServicesRoute,
  AdminInfrastructureStorageRoute: AdminInfrastructureStorageRoute,
  AdminLicensingCustomersRoute: AdminLicensingCustomersRoute,
  AdminLicensingFeaturesRoute: AdminLicensingFeaturesRoute,
  AdminLicensingInstallationsRoute: AdminLicensingInstallationsRoute,
  AdminLicensingLeasesRoute: AdminLicensingLeasesRoute,
  AdminLicensingPlansRoute: AdminLicensingPlansRoute,
  AdminLicensingProductsRoute: AdminLicensingProductsRoute,
  AdminLicensingRevocationsRoute: AdminLicensingRevocationsRoute,
  AdminObservabilityAlertsRoute: AdminObservabilityAlertsRoute,
  AdminObservabilityLogsRoute: AdminObservabilityLogsRoute,
  AdminObservabilityMetricsRoute: AdminObservabilityMetricsRoute,
  AdminObservabilityPrometheusRoute: AdminObservabilityPrometheusRoute,
  AdminPkiExpirationRoute: AdminPkiExpirationRoute,
  AdminPkiRevocationRoute: AdminPkiRevocationRoute,
  AdminPkiRotationRoute: AdminPkiRotationRoute,
  AdminProvidersProviderIdRoute: AdminProvidersProviderIdRoute,
  AdminSaasClientsRoute: AdminSaasClientsRoute,
  AdminSaasInstancesRoute: AdminSaasInstancesRoute,
  AdminSecurityAuthenticationRoute: AdminSecurityAuthenticationRoute,
  AdminSecurityAuthorizationRoute: AdminSecurityAuthorizationRoute,
  AdminSecurityEventsRoute: AdminSecurityEventsRoute,
  AdminSecurityFailedAttemptsRoute: AdminSecurityFailedAttemptsRoute,
  AdminSecurityFirewallRoute: AdminSecurityFirewallRoute,
  AdminSecuritySessionsRoute: AdminSecuritySessionsRoute,
  AdminBackupsIndexRoute: AdminBackupsIndexRoute,
  AdminLicensingIndexRoute: AdminLicensingIndexRoute,
  AdminObservabilityIndexRoute: AdminObservabilityIndexRoute,
  AdminProvidersIndexRoute: AdminProvidersIndexRoute,
  AdminSecurityIndexRoute: AdminSecurityIndexRoute,
  AdminLicensingLicensesIdRoute: AdminLicensingLicensesIdRoute,
  AdminPkiCertificatesIdRoute: AdminPkiCertificatesIdRoute,
  AdminSaasApplicationsIdRoute: AdminSaasApplicationsIdRoute,
  AdminLicensingLicensesIndexRoute: AdminLicensingLicensesIndexRoute,
  AdminPkiCertificatesIndexRoute: AdminPkiCertificatesIndexRoute,
  AdminSaasApplicationsIndexRoute: AdminSaasApplicationsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  DocsRoute: DocsRoute,
  LoginRoute: LoginRoute,
  StatusRoute: StatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
