/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AdminOverviewRouteImport } from './routes/_admin.overview'
import { Route as AdminInfrastructureComputeRouteImport } from './routes/_admin.infrastructure.compute'
import { Route as AdminInfrastructureHostsRouteImport } from './routes/_admin.infrastructure.hosts'
import { Route as AdminInfrastructureStorageRouteImport } from './routes/_admin.infrastructure.storage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInfrastructureComputeRoute =
  AdminInfrastructureComputeRouteImport.update({
    id: '/infrastructure/compute',
    path: '/infrastructure/compute',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminInfrastructureHostsRoute =
  AdminInfrastructureHostsRouteImport.update({
    id: '/infrastructure/hosts',
    path: '/infrastructure/hosts',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminInfrastructureStorageRoute =
  AdminInfrastructureStorageRouteImport.update({
    id: '/infrastructure/storage',
    path: '/infrastructure/storage',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/overview': typeof AdminOverviewRoute
  '/infrastructure/compute': typeof AdminInfrastructureComputeRoute
  '/infrastructure/hosts': typeof AdminInfrastructureHostsRoute
  '/infrastructure/storage': typeof AdminInfrastructureStorageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/overview': typeof AdminOverviewRoute
  '/infrastructure/compute': typeof AdminInfrastructureComputeRoute
  '/infrastructure/hosts': typeof AdminInfrastructureHostsRoute
  '/infrastructure/storage': typeof AdminInfrastructureStorageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_admin/overview': typeof AdminOverviewRoute
  '/_admin/infrastructure/compute': typeof AdminInfrastructureComputeRoute
  '/_admin/infrastructure/hosts': typeof AdminInfrastructureHostsRoute
  '/_admin/infrastructure/storage': typeof AdminInfrastructureStorageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/overview'
    | '/infrastructure/compute'
    | '/infrastructure/hosts'
    | '/infrastructure/storage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/overview'
    | '/infrastructure/compute'
    | '/infrastructure/hosts'
    | '/infrastructure/storage'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_admin/overview'
    | '/_admin/infrastructure/compute'
    | '/_admin/infrastructure/hosts'
    | '/_admin/infrastructure/storage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/overview': {
      id: '/_admin/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/infrastructure/compute': {
      id: '/_admin/infrastructure/compute'
      path: '/infrastructure/compute'
      fullPath: '/infrastructure/compute'
      preLoaderRoute: typeof AdminInfrastructureComputeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/infrastructure/hosts': {
      id: '/_admin/infrastructure/hosts'
      path: '/infrastructure/hosts'
      fullPath: '/infrastructure/hosts'
      preLoaderRoute: typeof AdminInfrastructureHostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/infrastructure/storage': {
      id: '/_admin/infrastructure/storage'
      path: '/infrastructure/storage'
      fullPath: '/infrastructure/storage'
      preLoaderRoute: typeof AdminInfrastructureStorageRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminOverviewRoute: typeof AdminOverviewRoute
  AdminInfrastructureComputeRoute: typeof AdminInfrastructureComputeRoute
  AdminInfrastructureHostsRoute: typeof AdminInfrastructureHostsRoute
  AdminInfrastructureStorageRoute: typeof AdminInfrastructureStorageRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOverviewRoute: AdminOverviewRoute,
  AdminInfrastructureComputeRoute: AdminInfrastructureComputeRoute,
  AdminInfrastructureHostsRoute: AdminInfrastructureHostsRoute,
  AdminInfrastructureStorageRoute: AdminInfrastructureStorageRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
